# Generated by Django 4.1.6 on 2023-02-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
